- name: Run geerlingguy.nginx role
  include_role:
    name: geerlingguy.nginx

- name: Install GoAccess to generate stats from access logs
  ansible.builtin.apt:
    name: goaccess
    state: present
    update_cache: yes
  
- include_tasks: custom_conf.yml

- include_tasks: webroot.yml

- include_tasks: logrotate.yml

- include_tasks: fail2ban.yml