---

- name: Schedule monitoring crontab - ip (every hour at 10 minutes past).
  cron:
    name: "monitoring ip"
    minute: "10"
    job: "/home/bgiarrizzo/.local/scripts/monitoring.sh ip > ~/monitoring_ip.log"
    user: bgiarrizzo

- name: Schedule monitoring crontab - load (every minute).
  cron:
    name: "monitoring load"
    minute: "*"
    job: "/home/bgiarrizzo/.local/scripts/monitoring.sh load > ~/monitoring_load.log"
    user: bgiarrizzo

- name: Schedule monitoring crontab - cpu (every minute).
  cron:
    name: "monitoring cpu"
    minute: "*"
    job: "/home/bgiarrizzo/.local/scripts/monitoring.sh cpu > ~/monitoring_cpu.log"
    user: bgiarrizzo

- name: Schedule monitoring crontab - ram (every minute).
  cron:
    name: "monitoring ram"
    minute: "*"
    job: "/home/bgiarrizzo/.local/scripts/monitoring.sh ram > ~/monitoring_ram.log"
    user: bgiarrizzo

- name: Schedule monitoring crontab - disk (every hour at 0 minutes past).
  cron:
    name: "monitoring disk"
    minute: "0"
    job: "/home/bgiarrizzo/.local/scripts/monitoring.sh disk > ~/monitoring_disk.log"
    user: bgiarrizzo

- name: Schedule monitoring crontab - certs (every day at 10:30).
  cron:
    name: "monitoring certs"
    minute: "30"
    hour: "10"
    job: "/home/bgiarrizzo/.local/scripts/monitoring.sh certs > ~/monitoring_certs.log"
    user: bgiarrizzo
